networks:
  common-network:
    external: true

services:
  slayfridaybot:
    build:
      context: .
      dockerfile: ./Dockerfile
    image: slayfridaybot:latest
    env_file:
      - .env
    environment:
      - RUST_LOG=info
    volumes:
      - ./sticker_storage.json:/app/sticker_storage.json
    networks:
      - common-network
    restart: unless-stopped