networks:
  slay-network:
    driver: bridge

services:
  slayfridaybot:
    build:
      context: .
      dockerfile: ./Dockerfile
    image: slayfridaybot:latest
    env_file:
      - .env
    environment:
      - RUST_LOG=info
    volumes:
      - ./sticker_storage.json:/app/sticker_storage.json
    networks:
      - slay-network
    restart: unless-stopped
    depends_on:
      - xray-proxy

  xray-proxy:
    image: teddysun/xray:latest
    container_name: xray-proxy
    command: [ "xray", "run", "-c", "/etc/xray/config.json" ]
    volumes:
      - ./xray-config.json:/etc/xray/config.json:ro
    ports:
      - "8100:8100"
    restart: unless-stopped
    networks:
      - slay-network
