services:
  slayfridaybot:
    image: ghcr.io/jojosoderqvist/slay-friday-bot:main
    container_name: slayfridaybot
    env_file:
      - .env
    environment:
      - RUST_LOG=info
    volumes:
      - ./sticker_storage.json:/app/sticker_storage.json
    networks:
      - slay-network
    restart: unless-stopped
    depends_on:
      - xray-proxy
      - loki

  xray-proxy:
    image: teddysun/xray:26.2.6
    container_name: xray-proxy
    command: [ "xray", "run", "-c", "/etc/xray/config.json" ]
    volumes:
      - ./xray-config.json:/etc/xray/config.json:ro
    ports:
      - "8100:8100"
    restart: unless-stopped
    networks:
      - slay-network

  loki:
    image: grafana/loki:3.5.10
    container_name: loki
    ports:
      - "3100:3100"
    volumes:
      - ./loki-config.yaml:/etc/loki/local-config.yaml
      - loki_data:/loki
    command: -config.file=/etc/loki/local-config.yaml
    networks:
      - slay-network

  grafana:
    image: grafana/grafana:12.0
    container_name: grafana
    env_file:
      - .env
    ports:
      - "3000:3000"
    volumes:
      - grafana_data:/var/lib/grafana
    environment:
      - GF_SECURITY_ADMIN_USER=${GF_USER}
      - GF_SECURITY_ADMIN_PASSWORD=${GF_PASSWORD}
    depends_on:
      - loki
    networks:
      - slay-network

volumes:
  loki_data:
  grafana_data:

networks:
  slay-network:
    driver: bridge